# Generated by Django 5.1.2 on 2025-08-06 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Neutered', 'Neutered')], max_length=10)),
                ('preferred_time', models.CharField(choices=[('Morning', 'Morning (6-9 AM)'), ('Midday', 'Midday (11 AM - 2 PM)'), ('Afternoon', 'Afternoon (3-6 PM)'), ('Evening', 'Evening (6-9 PM)')], max_length=20)),
                ('breed', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('health_states', models.JSONField(default=list)),
                ('characters', models.JSONField(default=list)),
                ('red_flags', models.JSONField(default=list)),
                ('photos', models.JSONField(default=list)),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to='api.pet')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
