# nixpacks.toml — 延迟数据库迁移到运行时执行
providers = []

[phases.setup]
# 安装带 pip 的 Python
nixPkgs = ["python311Full", "poetry", "gcc", "postgresql"]

[phases.build]
cmds = [
  "echo 'Building without touching the database...'",
  "pip install -r requirements.txt"
]

[start]
cmd = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn petpal.wsgi:application --bind 0.0.0.0:$PORT --workers 3"