# Nixpacks configuration for Railway deployment
# Railway will automatically detect and use requirements.txt

[variables]
    NIXPACKS_PYTHON_VERSION = "3.11"

# No build commands - avoid database access during build

[start]
    cmd = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn petpal.wsgi:application --bind 0.0.0.0:$PORT --workers 3"