# Nixpacks configuration for Railway deployment
# Railway will automatically detect and use requirements.txt

[variables]
    NIXPACKS_PYTHON_VERSION = "3.11"

[phases.build]
    cmds = [
        "python manage.py collectstatic --noinput"
    ]

[start]
    cmd = "gunicorn petpal.wsgi:application --bind 0.0.0.0:$PORT --workers 3"