# nixpacks.toml — 明确启用 Python provider 来确保 pip 可用
providers = ["python"]

[phases.setup]
# 使用带 pip 的 Python
nixPkgs = ["python311Full", "gcc", "postgresql"]

[phases.build]
cmds = [
  "echo 'Building without touching the database...'"
  # 无需手动安装依赖，让 provider 来处理 pip install
]

[start]
cmd = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn petpal.wsgi:application --bind 0.0.0.0:$PORT --workers 3"