# nixpacks.toml — 延迟数据库迁移到运行时执行
providers = []

[phases.setup]
nixPkgs = ["python311", "poetry", "gcc", "postgresql"]  # 或你需要的 Python/DB 构建依赖

[phases.build]
cmds = [
  "echo 'Building without touching the database...'",
  "pip install -r requirements.txt"
]

[start]
cmd = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn petpal.wsgi:application --bind 0.0.0.0:$PORT --workers 3"